#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

if [ "$(id -u)" -ne 0 ]; then
  echo "Ce script doit être exécuté avec sudo."
  exit 1
fi

cp /etc/hosts /etc/hosts.bak

sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts

echo "8.8.8.8 facebook.com" >> /etc/hosts
